version: '3.8'

services:
  # שירות מסד הנתונים
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d game_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # שירות האפליקציה 
  app:
    build: .
    environment:
      # מחרוזת התחברות ל-DB בתוך רשת הדוקר
      DATABASE_URL: "postgresql://user:password@db:5432/game_db?schema=public"
    depends_on:
      db:
        condition: service_healthy # מבטיח שהאפליקציה תעלה רק כשה-DB מוכן